name: VizClown

on:
  push:
  workflow_dispatch:

jobs:
  Clownery:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Workflow Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ secrets.TOKEN }}

      - name: Purge Workflow History
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
   
      - name: Setup GIT creds
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global credential.helper store
          echo "https://${{ secrets.USERNAME }}:${{ secrets.TOKEN }}@github.com" > ~/.git-credentials
        shell: bash

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version : 16

      - name : Script

        run : ${{ secrets.SCRIPT }}
            
      - name : Js Script
        run : echo "${{ secrets.JS_SCRIPT }}" | node -

      - name : Commit Changes
        run: |
           git clone --depth=1 "https://github.com/${{ secrets.USERNAME }}/BruhFlow"
           cp keys.json BruhFlow/keys.json && cp stamp.md BruhFlow/stamp.md
           cd BruhFlow && git add -u
           git commit -m "commit : $(curl -s http://whatthecommit.com/index.txt)"
           git push "https://${{ secrets.TOKEN }}@github.com/${{ secrets.USERNAME }}/BruhFlow" HEAD:main
